### ISSUE TITLE
Electron-amd example does not work with latest electron

### ISSUE THREAD

**Issue by vadi2** [Microsoft/monaco-editor-samples#16]
I'm getting the following error trying to run the Electron example:

```
Failed to load resource: net::ERR_FILE_NOT_FOUND
electron-index.html:36 Uncaught TypeError: amdRequire.config is not a function
    at electron-index.html:36
```

![monaco editor _091](https://user-images.githubusercontent.com/110988/37451900-562bb9f2-2833-11e8-9ba1-341c04288cde.png)

Latest monaco-editor-samples and electron are used:

```
vadi@volga:~/Programs/monaco-editor-samples$ git pull
Already up-to-date.
Current branch master is up to date.
vadi@volga:~/Programs/monaco-editor-samples$ cd electron-amd/
vadi@volga:~/Programs/monaco-editor-samples/electron-amd$ electron --version
v2.0.0-beta.3
vadi@volga:~/Programs/monaco-editor-samples/electron-amd$ electron main.js
```

**Comment by alexandrudima** [comment]
That is most weird, I will have to try on Linux, as this works for me on OSX:

![image](https://user-images.githubusercontent.com/5047891/37456148-fdbb2062-283e-11e8-82d5-b9d29865664e.png)

**Comment by alexandrudima** [comment]
This also works for me on Linux:

Have you executed `npm install .` in the root of the repo ?

![image](https://user-images.githubusercontent.com/5047891/37458790-6802303a-2846-11e8-842c-a9e3da47908d.png)

**Comment by vadi2** [comment]
That worked - thanks!
