### ISSUE TITLE
webpack bundle file size is too large

### ISSUE THREAD

**Issue by JavaCS3** [microsoft/monaco-editor-samples#17]
The webpack output bundle.js is really big. Is there any way to minimize this?
And I found `monaco-editor/min/vs/editor/editor.main.js` is 1.9MB.

```
➜  browser-esm-webpack-small git:(master) ✗ webpack
Hash: f91dc72ad575ea523738
Version: webpack 4.1.1
Time: 18790ms
Built at: 2018/3/18 下午11:28:01
                  Asset      Size  Chunks                    Chunk Names
            0.bundle.js  2.95 KiB       0  [emitted]
editor.worker.bundle.js   112 KiB       1  [emitted]         editor.worker
          app.bundle.js  1.34 MiB       2  [emitted]  [big]  app
Entrypoint app [big] = app.bundle.js
Entrypoint editor.worker = editor.worker.bundle.js
  [42] (webpack)/buildin/global.js 509 bytes {1} {2} [built]
  [47] ./node_modules/monaco-editor/esm/vs/base/browser/ui/scrollbar/scrollableElement.js + 6 modules 54.4 KiB {2} [built]
       |    7 modules
  [48] ./node_modules/monaco-editor/esm/vs/editor/common/services/editorSimpleWorker.js + 6 modules 106 KiB {1} {2} [built]
       |    7 modules
  [51] ./node_modules/monaco-editor/esm/vs/base/browser/ui/selectBox/selectBox.js + 7 modules 113 KiB {2} [built]
       |    8 modules
  [53] ./index.js + 238 modules 2.54 MiB {2} [built]
       | ./index.js 7.41 KiB [built]
       |     + 238 hidden modules
    + 127 hidden modules

WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web performance.
Assets:
  app.bundle.js (1.34 MiB)

WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
Entrypoints:
  app (1.34 MiB)
      app.bundle.js
```

```
➜  browser-esm-webpack-small git:(master) ✗ webpack --json | webpack-bundle-size-analyzer
monaco-editor: 911.49 KB (25.7%)
style-loader: 12.63 KB (0.357%)
setimmediate: 6.32 KB (0.179%)
process: 5.29 KB (0.149%)
css-loader: 2.21 KB (0.0623%)
timers-browserify: 1.85 KB (0.0523%)
webpack: 509 B (0.0140%)
<self>: 2.54 MB (73.4%)

Note: The file sizes are calculated before minification, and might not reflect the real file sizes in the production bundle.
```

**Comment by alexandrudima** [comment]
Not that I am aware of.

**Comment by haxaco** [comment]
I'm getting the same issue, bundling results in a very large file size:

`> webpack --config webpack.config.js

Hash: 165de46c03eed2dc1624
Version: webpack 4.1.1
Time: 4602ms
Built at: 4/5/2018 2:59:03 PM
                  Asset      Size         Chunks                    Chunk Names
           36.bundle.js  4.32 KiB             36  [emitted]
           18.bundle.js  5.63 KiB             18  [emitted]
           40.bundle.js  68.9 KiB             40  [emitted]
           39.bundle.js  66.7 KiB             39  [emitted]
           38.bundle.js  5.75 MiB             38  [emitted]  [big]
           37.bundle.js   140 KiB             37  [emitted]
            0.bundle.js  7.63 KiB              0  [emitted]
            1.bundle.js  4.13 KiB              1  [emitted]
            2.bundle.js   9.2 KiB              2  [emitted]
            3.bundle.js  7.16 KiB              3  [emitted]
            4.bundle.js  22.8 KiB              4  [emitted]
            5.bundle.js  10.9 KiB              5  [emitted]
            6.bundle.js  4.35 KiB              6  [emitted]
            7.bundle.js  18.3 KiB              7  [emitted]
            8.bundle.js  17.1 KiB              8  [emitted]
            9.bundle.js  6.49 KiB              9  [emitted]
           10.bundle.js  13.8 KiB             10  [emitted]
           11.bundle.js  6.65 KiB             11  [emitted]
           12.bundle.js  6.85 KiB             12  [emitted]
           13.bundle.js    10 KiB             13  [emitted]
           14.bundle.js  7.42 KiB             14  [emitted]
           15.bundle.js  19.8 KiB             15  [emitted]
           16.bundle.js  13.3 KiB             16  [emitted]
           17.bundle.js  24.8 KiB             17  [emitted]
          app.bundle.js  6.45 MiB            app  [emitted]  [big]  app
           19.bundle.js  20.9 KiB             19  [emitted]
           20.bundle.js  8.05 KiB             20  [emitted]
           21.bundle.js  8.09 KiB             21  [emitted]
           22.bundle.js  4.98 KiB             22  [emitted]
           23.bundle.js  6.86 KiB             23  [emitted]
           24.bundle.js  6.33 KiB             24  [emitted]
           25.bundle.js  3.12 KiB             25  [emitted]
           26.bundle.js  8.28 KiB             26  [emitted]
           27.bundle.js  10.4 KiB             27  [emitted]
           28.bundle.js  6.33 KiB             28  [emitted]
           29.bundle.js  6.06 KiB             29  [emitted]
           30.bundle.js  4.91 KiB             30  [emitted]
           31.bundle.js  7.85 KiB             31  [emitted]
           32.bundle.js  3.12 KiB             32  [emitted]
           33.bundle.js  8.47 KiB             33  [emitted]
           34.bundle.js  9.69 KiB             34  [emitted]
           35.bundle.js  7.47 KiB             35  [emitted]
   css.worker.bundle.js  1.48 MiB     css.worker  [emitted]  [big]  css.worker
editor.worker.bundle.js   462 KiB  editor.worker  [emitted]  [big]  editor.worker
  html.worker.bundle.js   867 KiB    html.worker  [emitted]  [big]  html.worker
  json.worker.bundle.js   767 KiB    json.worker  [emitted]  [big]  json.worker
    ts.worker.bundle.js  7.86 MiB      ts.worker  [emitted]  [big]  ts.worker
           41.bundle.js  31.4 KiB             41  [emitted]
Entrypoint app [big] = app.bundle.js
Entrypoint editor.worker [big] = editor.worker.bundle.js
Entrypoint json.worker [big] = json.worker.bundle.js
Entrypoint css.worker [big] = css.worker.bundle.js
Entrypoint html.worker [big] = html.worker.bundle.js
Entrypoint ts.worker [big] = ts.worker.bundle.js
[./index.js] 629 bytes {app} [built]
[./node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 509 bytes {ts.worker} {html.worker} {css.worker} {json.worker} {editor.worker} {app} [built]
[./node_modules/webpack/buildin/harmony-module.js] (webpack)/buildin/harmony-module.js 597 bytes {ts.worker} {38} [built]
    + 745 hidden modules
`

`> webpack --json | webpack-bundle-size-analyzer

monaco-editor: 14.09 MB (99.8%)
<self>: 29.99 KB (0.207%)`

**Comment by alexdima** [comment]
There are samples for how to make the webpack size smaller.
