### ISSUE TITLE
Including monaco-editor into a page where requirejs is already loaded/available

### ISSUE THREAD

**Issue by estruyf** [Microsoft/monaco-editor-samples#19]
Is there a way to include the `loader.js` in environment where `requirejs` is already loaded?

What I saw is that monaco-editor is using its own loader, which also exposes `require`. It seems when I async load the loader, it doesn't bind the new one automatically. Is there a way to trigger this? Already tried to call `AMDLoader.init()`, but in that case I'm unable to configure the config.

Once I call `require.config({paths: {'vs': 'https://cdnjs.cloudflare.com/ajax/libs/monaco-editor/0.11.1/min/vs'}});`, I get the following error:

```
TypeError: Cannot read property 'configure' of null
```

**Comment by alexandrudima** [comment]
https://github.com/Microsoft/monaco-editor-samples/blob/master/browser-amd-requirejs/index.html
