### ISSUE TITLE
Add an advanced TypeScript sample

### ISSUE THREAD

**Issue by T18970237136** [Microsoft/monaco-editor-samples#2]
Hi, thanks for sharing the samples!

Could you add a sample showing how to use the Editor in a HTML page with custom [Typescript Compiler options](https://www.typescriptlang.org/docs/handbook/compiler-options.html), e.g. `noLib`, `noImplicitAny`, `target` etc., and how to add your own libs (`d.ts`), ideally from a string or data URL, alternatively from other URLs/files?
(This would be what we need, as we want to embed the editor in a HTML page where the user can edit custom scripts, and we want to supply custom .d.ts files read from the DB that the javascript has as a string.

Thank you!

**Comment by T18970237136** [comment]
I just found [this example](https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-configure-javascript-defaults) which sets TS Compiler options and adds extra libs from strings (exactly what I need), however for JavaScript instead of TypeScript.

I tried the following JS code in a HTML file to use TypeScript mode and set TS Compiler Options:
```javascript
require.config({ paths: { 'vs': 'node_modules/monaco-editor/min/vs' }});
require(['vs/editor/editor.main'], function() {
	
	// compiler options
	monaco.languages.typescript.typescriptDefaults.setCompilerOptions({
		target: monaco.languages.typescript.ScriptTarget.ES5,
		noEmit: true,
		noLib: true
	});

	// extra libraries
	monaco.languages.typescript.typescriptDefaults.addExtraLib([
		'declare class Facts {',
		'    /**',
		'     * Returns the next fact',
		'     */',
		'    static next():string',
		'}',
	].join('\n'), 'filename/facts.d.ts');

	var editor = monaco.editor.create(document.getElementById('container'), {
		value: [
			'function x() {',
			'\tconsole.log("Hello world!");',
			'}'
		].join('\n'),
		language: 'typescript'
	});
});
```
The editor loads, but unfortunately the dev console shows an error `Could not find file: 'inmemory://model/1'.`, and the typescript mode doesn't work. If I remove the `setCompilerOptions` then it works again.
Can you give me a hint how to change this code to make it work with setting the custom compiler options?

Thanks!

**Comment by T18970237136** [comment]
I found the cause of the failure: I didn't set the `allowNonTsExtensions: true` option, which was set by default. After I set it to true, the Typescript mode is now working correctly.
Thanks

**Comment by T18970237136** [comment]
Hi,
It turns out that in my case there's still an unresolved issue:

How to correctly open and close the Monaco editor multiple times, each time using a different set of TypeScript Libs?

E.g. when a HTML page displays a table and for each entry a Monaco Editor should be opened and then closed. I think when closing the editor I need to call `editor.dispose();`.
However, another problem is, how can I use different sets of TypeScript Lib Files for each editor instance? 
`monaco.languages.typescript.typescriptDefaults.addExtraLib()` seems to only allow to add libs, not not remove/clear existing ones. However I would need to remove the existing libs and add new ones before opening the editor another time.

Can you add a example that shows this or give me a hint how to do this correctly?

Thanks!

**Comment by alexandrudima** [comment]
`addExtraLib` returns an `IDisposable`. I think calling `.dispose()` on it will remove the extra lib. But @jrieken will know best.

**Comment by alexandrudima** [comment]
@jrieken ?

**Comment by alexandrudima** [comment]
@jrieken Is this already fixed in monaco-typescript?

**Comment by jrieken** [comment]
Yes - that's fixed

**Comment by T18970237136** [comment]
Thanks!
For reference: https://github.com/Microsoft/monaco-typescript/issues/5

**Comment by shivajivarma** [comment]
Hi @T18970237136, 
Dispose is removing the lib from all the instances. How did you achieve your usecase? different set of libs for each instance?
