### ISSUE TITLE
Error when run the browser-esm-webpack sample

### ISSUE THREAD

**Issue by FrankFang** [microsoft/monaco-editor-samples#21]
![](https://i.loli.net/2018/04/07/5ac887084fcb1.jpg)

Steps to reproduce:

1. `npm i .`
2. `./node_modules/.bin/webpack`
3. open dist/index.html
4. open console

**Comment by alexandrudima** [comment]
Please follow all steps i.e. https://github.com/Microsoft/monaco-editor-samples#running

![image](https://user-images.githubusercontent.com/5047891/38569368-5d7825c0-3ceb-11e8-8e2c-16e2b6fe3f30.png)

i.e. `npm run simpleserver`
and then access the sample via `localhost:8888`.

**Comment by alexandrudima** [comment]
More information is available at the provided link in the dev tools https://github.com/Microsoft/monaco-editor#faq

**Comment by MarceloBarrera** [comment]
@FrankFang You could add the following on the package.json located in the example folder (browser-esm-webpack):
  "scripts": {
    "build": "webpack --config webpack.config.js"
  } 
and then do:  npm run build
