### ISSUE TITLE
Problem running browser-esm-webpack on IE 11

### ISSUE THREAD

**Issue by acautin** [Microsoft/monaco-editor-samples#24]
I am having 2 issues with the editor, first I tried to bundle it into my own project and everything was working fine until I tried to use it on IE, there mouse events are not working and it is impossible to select anything inside the editor using the mouse.
Then tried to run the example to see if it was working but I get errors and it is not loading anything. Did the installation as explained in the index and running using simple server, again no issues when trying from firefox.
Simpleserver is running on OS X, in case makes any difference. 

![screen shot 2018-05-03 at 11 08 25](https://user-images.githubusercontent.com/949102/39568548-daf6d79c-4ec2-11e8-8e0c-083c6bf0d8e9.png)

**Comment by alexandrudima** [comment]
Have you seen https://github.com/Microsoft/monaco-editor#known-issues

![image](https://user-images.githubusercontent.com/5047891/39569280-06afe9f8-4ec5-11e8-85ba-848955403852.png)

**Comment by acautin** [comment]
@alexandrudima thank you for the quick response and sorry I missed the known issues. Any idea regarding the sample errors ?

**Comment by alexandrudima** [comment]
I can reproduce in IE11.

The exception comes right when doing a dynamic require:

```
function getMode() {
    return monaco.Promise.wrap(__webpack_require__.e(/*! import() */ 40).then(__webpack_require__.bind(null, /*! ./tsMode.js */ "./node_modules/monaco-editor/esm/vs/language/typescript/tsMode.js")));
}

...

monaco.languages.onLanguage('javascript', function () {
    return getMode().then(function (mode) { return mode.setupJavaScript(javascriptDefaults); });
});

```

I can only speculate that perhaps webpack does not support IE11 ? I am not a webpack expert...

**Comment by alexandrudima** [comment]
To make matters worse, it appears there is no way to debug webpack generated source code in IE11... Due to the heavy use of `eval`, all breakpoints are lost in between runs...

**Comment by acautin** [comment]
@alexandrudima well that is a pity, it is working without issues with webpack 3.10.0 which is the one we are using currently in our project. Thanks again for the help.
