### ISSUE TITLE
Do not understand `self.MonacoEnvironment` in Parcel example

### ISSUE THREAD

**Issue by habemus-papadum** [Microsoft/monaco-editor-samples#28]
Hi -- Thanks for adding the ParcelJS example -- definitely a nice way to get started with minimal fuss. 

I don't understand where the variable `self` is being define in the line `self.MonacoEnvironment = ...`

I can see where it is defined in the webpack config, but I don't understand how(or if) it is being defined by parceljs.    Is there an easy explanation for what is going on? 

 thanks, nehal

**Comment by alexandrudima** [comment]
`self` is an alias for the global object. In this context, it could have been written like `window.MonacoEnvironment = ...`. The advantage of `self` is that it works both in the UI thread and in web workers.

So, that line defines a global variable called `MonacoEnvironment`. The editor, when constructing a web worker, will look if such a global variable exists, and call the respective methods as necessary. i.e. https://github.com/Microsoft/vscode/blob/9b4316b8fe2109f17d50343e56c1a0c1eb046eaf/src/vs/base/worker/defaultWorkerFactory.ts#L10-L26

**Comment by habemus-papadum** [comment]
Thanks -- That is perfectly clear (and apologies for being slightly off topic -- I had never seen `self` in the wild before) 
nehal
