### ISSUE TITLE
`browser-esm-parcel` could not load workers

### ISSUE THREAD

**Issue by varHarrie** [Microsoft/monaco-editor-samples#29]
I clone [the project](https://github.com/Microsoft/monaco-editor-samples/blob/master/browser-esm-parcel/src/index.js) and simply change language to `javascript`:

```javascript
import 'monaco-editor/esm/vs/language/typescript/monaco.contribution'; // <---

monaco.editor.create(document.getElementById('container'), {
	value: [
		'const a = 5',
		'const b = 3',
		'console.log(a + b)'
	].join('\n'),
	language: 'javascript' // <---
});
```

And I build with `parcel build src/index.html` and run `dist/index.html`.

It shows error:

![image](https://user-images.githubusercontent.com/14304201/40895854-4923c57e-67e4-11e8-8265-0778481bf9fc.png)

**Comment by rebornix** [comment]
I updated the parcel sample so it can now work without the error of missing workers.

To enable JavaScript or TypeScript features, please uncomment below lines

```js
import 'monaco-editor/esm/vs/language/typescript/monaco.contribution';
import 'monaco-editor/esm/vs/basic-languages/javascript/javascript.contribution';
import 'monaco-editor/esm/vs/basic-languages/typescript/typescript.contribution';
```
