### ISSUE TITLE
Loading through requirejs should not assign it to window

### ISSUE THREAD

**Issue by brijeshb42** [Microsoft/monaco-editor-samples#30]
In this example in the [sample](https://github.com/Microsoft/monaco-editor-samples/blob/master/browser-amd-editor/index.html)

```js
require(['vs/editor/editor.main'], function() {
    // here monaco is a global variable
});
```

Ideally, the `function` should get `monaco` as the first parameter. Or is there any way this can be achieved right now?

**Comment by alexandrudima** [comment]
Yes, the function also receives the API.

```
require(['vs/editor/editor.main'], function(_monaco) {
    // window.monaco or _monaco both work
});
```

**Comment by brijeshb42** [comment]
This does not happen right now. Here is a fiddle with the demo - http://jsfiddle.net/t7mfr02q/20/embedded/result,js/

**Comment by alexandrudima** [comment]
Thank you. I can reproduce. I've moved the issue to https://github.com/Microsoft/monaco-editor/issues/922
