### ISSUE TITLE
No sample using Typescript

### ISSUE THREAD

**Issue by sebdoucet** [microsoft/monaco-editor-samples#33]
Hi,

I try to setup a project using typescript... At first using SystemJS as module loader and now using AMD but either of these solution works, I can not find why, nothing append, no error.

I've see sample using webpack but no one using Typescript...

Sébastien.

**Comment by alexdima** [comment]
There is now a sample at https://github.com/microsoft/monaco-editor-samples/tree/master/browser-esm-webpack-typescript
