### ISSUE TITLE
Provide example of cross-origin ESM usage

### ISSUE THREAD

**Issue by peterschussheim** [microsoft/monaco-editor-samples#35]
I've reviewed the samples and [this doc](https://github.com/Microsoft/monaco-editor/blob/master/docs/integrate-esm.md) and [this one](https://github.com/Microsoft/monaco-editor/blob/master/docs/integrate-amd-cross.md), however, I am still unclear how to integrate ESM version correctly.

It is a bit confusing because the webpack examples in this repo do not use [monaco-editor-webpack-plugin](https://github.com/Microsoft/monaco-editor-webpack-plugin).

An example showing exactly how to do this would be appreciated.

**Comment by Phinome** [comment]
+1

**Comment by alexdima** [comment]
There is now a sample that [uses the `monaco-editor-webpack-plugin`](https://github.com/microsoft/monaco-editor-samples/tree/master/browser-esm-webpack-monaco-plugin) and that plugin will soon (with the next version) support [cross-origin web workers automatically](https://github.com/microsoft/monaco-editor-webpack-plugin/commit/802217b8774385b18b9a79159981029cc429cd9e)
