### ISSUE TITLE
ESM issue with link.js

### ISSUE THREAD

**Issue by atomicpages** [microsoft/monaco-editor-samples#36]
Importing `link.js` in the parcel package is leading to an error using Monaco 0.15.6 and parcel 1.11.0. Not sure if this is a known issue or not.

Here's an exact repro:

```js
import 'monaco-editor/esm/vs/editor/browser/controller/coreCommands.js';
import 'monaco-editor/esm/vs/editor/browser/widget/codeEditorWidget.js';
import 'monaco-editor/esm/vs/editor/contrib/links/links.js';
import * as monaco from 'monaco-editor/esm/vs/editor/editor.api.js';
import 'monaco-editor/esm/vs/language/typescript/monaco.contribution';
import 'monaco-editor/esm/vs/basic-languages/javascript/javascript.contribution';

self.MonacoEnvironment = {
	getWorker: function (moduleId, label) {
		if (label === 'typescript' || label === 'javascript') {
			return new Worker('../node_modules/monaco-editor/esm/vs/language/typescript/ts.worker.js')
		}

		return new Worker('../node_modules/monaco-editor/esm/vs/editor/editor.worker.js')
	}
}

monaco.editor.create(document.getElementById('container'), {
	value: `import * as React from 'react';
import ReactDOM from 'react-dom';
	
function App() {
	return <p>Hello</p>;
}

ReactDOM.render(<App />, document.querySelector('#app'));`,
	language: 'javascript',
	theme: 'vs-dark'
});
```

![image](https://user-images.githubusercontent.com/1824291/52614003-0e5b5b00-2e45-11e9-9758-34c913c5fcf7.png)

**Comment by alexandrudima** [comment]
The `links` contribution is the only one you have in there that ends up causing a web worker instantiation (to compute links on the web worker). So, the problem is not with the `links.js` contribution, but with web workers. It looks like they are incorrectly packaged (syntax error).

**Comment by atomicpages** [comment]
Any ETA on when this will be fixed? 👍

**Comment by alexandrudima** [comment]
Did you try the updated parcel sample -- https://github.com/Microsoft/monaco-editor-samples/tree/master/browser-esm-parcel

**Comment by alexdima** [comment]
The update parcel sample works for me.
