### ISSUE TITLE
Readme suggestion

### ISSUE THREAD

**Issue by smellai** [Microsoft/monaco-editor-samples#4]
```
npm install monaco-editor-samples
cd node_modules/monaco-editor-samples
npm run simpleserver
```

This will create the following folder structure:
node_modules
                |____________ monaco-editor-samples
                |____________ monaco-editor

and will not work, because the correct structure should be:

monaco-editor-samples
                |____________ node_modules
                                                      |_________ monaco-editor

**Comment by alexandrudima** [comment]
README is now updated
