### ISSUE TITLE
window.require.config is not a function

### ISSUE THREAD

**Issue by zy823957866** [microsoft/monaco-editor-samples#40]
window.require.config({ paths: { 'vs': baseUrl + "/monaco/vs" } });

what can i do..

**Comment by nitslucky** [comment]
did you find the solution ?

**Comment by jonpc2018** [comment]
Update on a possible cause.
When including the BingMap api script, i.e.   <script type='text/javascript' src='http://www.bing.com/api/maps/mapcontrol' async defer></script>

seem to cause this error.

Possible solution
Step 1) Remove the bing map script from the index.html file
Step 2) Create a MonacoEditorLoader and load this in the app-root Angular component
Step 3) Create a BingMapsLoader and load this when the Map shows, i.e. after the   MonacoEditorLoader has loaded.
