### ISSUE TITLE
"require() is not defined" when starting electron-amd with Electron5.x

### ISSUE THREAD

**Issue by Symbolk** [microsoft/monaco-editor-samples#43]
Since in Electron 5.x, the default for nodeIntegration changed from true to false for security reasons, when you try to start the electron-amd with the latest Electron, the editor won't be correctly loaded for the "require() is not defined" error.

The quick solution is to enable nodeIntegration when creating the window. Since this is only a demo app, it works fine.

**Comment by Symbolk** [comment]
#44

**Comment by alexdima** [comment]
Fixed via https://github.com/microsoft/monaco-editor-samples/commit/17072a2c3621fcaa686cf89e6a6e9dc8c062b5ad
