### ISSUE TITLE
intellisense for C#

### ISSUE THREAD

**Issue by khalidcawl** [Microsoft/monaco-editor-samples#6]
The edit documentation on the main page says there is intellisense for only these languages/markups: TypeScript, JavaScript, CSS, LESS, SCSS, JSON, HTML.

Any reason why there is no intellisense for other languages? 
Thanks.

**Comment by cstff1** [comment]
Yes, should be.

**Comment by sr229** [comment]
There are intellisense support on other Languages but I believe either it was planned or only made possible via VSCode

**Comment by khalidcawl** [comment]
@sr229 That is what I thought as well. I hope it is planned, for if they allow it only on VSCode it would defeat the purpose of making this editor open source.

**Comment by alexandrudima** [comment]
Please see https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-completion-provider-example which documents how it is possible to add a completion item provider.

There are no plans to implement a C# language service in a web worker.
