### ISSUE TITLE
CSS dont affect on token style

### ISSUE THREAD

**Issue by Zmeu213** [Microsoft/monaco-editor-samples#9]
In `master/sample-monarch/index.html` styles doesnt work for me, I got plain black text. 
I can only add some colors to language tokens by defining theme like
```
const theme = {
  base: 'vs', 
  inherit: true,
  rules: [
    { token: 'custom-info', foreground: 'a3a7a9' },
    { token: 'custom-error', foreground: 'ee4444' },
    { token: 'custom-notice', foreground: '1055af' },
    { token: 'custom-date', foreground: '20aa20' },
  ]
}
```

and
 
```
monaco.editor.defineTheme('myTheme', theme)

var editor = monaco.editor.create(document.getElementById('container'), {
	value: getCode(),
	language: 'myCustomLanguage',
	theme: 'myTheme'
});
```
without theme all text has default `mtk1`class with black color. Is there a way to define custom class to a token?

**Comment by alexandrudima** [comment]
Thank you. Fixed the sample.

**Comment by andrienko** [comment]
Is there any way to assign the `className` to a language token without creating an entirely new theme?
Or can I always be sure the token name will be, say, `mtk6` and won't change?
